### ISSUE TITLE
в методе save нет проверки на существование элемента с индексом $id

### ISSUE THREAD

**Issue by cjbars** [VolginN/WEB#7]
Такого элемента может и не быть. Нужно обрабатывать эту ситуацию, иначе метод бесконтрольно добавит вам запись в базу

**Comment by VolginN** [comment]
в методе save добавил последним коммитом, а так же добавил подобную проверку в методе delete

**Comment by cjbars** [comment]
только надо вернуть false а не строку 404. Пофиксите чуть позже
